#!/bin/sh
#
# A POSIX shell script that checks flac files for upscaling, upsampling and other tricks that indicate a non-lossless source.
#
# Copyright (C) 2023 Dusan Mitrovic <dusan@dusanmitrovic.xyz>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Depends on:
#   - flac, A flac decoder (available in most distribution package managers)
#   - LAC, lossless audio checker (available here: https://losslessaudiochecker.com)
depends() {
    deps="flac LAC"
    for dep in $deps;
    do
        exists="$(command -v "$dep" | wc -l)"
        
        if [ "$exists" -eq 0 ]; then
            echo "Unsatisfied dependency: $dep" && exit 1
        fi
    done
}

check() {
    in="$1"
    out="$2"

    if ! flac --silent -d "$in" -o "$out"; then
        echo "Decoding of the flac file failed." && exit 1
    fi

    LAC "$out" | awk '/^Result/'
}

clean() {
    if [ -f "$1" ]; then
        rm "$1"
    fi
}

main() {
    depends

    in="$1"
    out="/tmp/sample.wav"

    check "$in" "$out"
    clean "$out"
}

main "$1"
